### ISSUE TITLE
SBayesR always imputes N

### ISSUE THREAD

**Issue by mja** [opain/GenoPred#108]
SBayesR script always inludes the `--impute-n` flag when running gctb, rather than setting it based on the script logic,  in the string 

```
'--exclude-mhc --burn-in 2000 --impute-n --out-freq 1000 --out '
                              ^^^^^^^^^^
```

 near the end of the line:

https://github.com/opain/GenoPred/blob/ef4e4b3faf4257ec44bfa8349d30eae9420f2542/Scripts/pgs_methods/sbayesr.R#L146

**Comment by opain** [comment]
Thanks for flagging Mark. I have just pushed a commit to the master branch that fixes it.
