### ISSUE TITLE
ldak dependency link dead.

### ISSUE THREAD

**Issue by yassineS** [opain/GenoPred#115]
https://github.com/opain/GenoPred/blob/b7ce68d23fe580a01c93f199950f17308d7a69ed/pipeline/rules/dependencies.smk#L462 references a dead link. This needs to be updated to ldak6, according to the details here: https://www.ldak-kvik.com/docs/downloads.

Thank you!

**Comment by opain** [comment]
Thank you for flagging this! I will consider updating to LDAK v6, but have also asked the developer of LDAK whether a legacy version of 5.1 is available somewhere for consistency. I will write back when I have resolved the issue.

**Comment by opain** [comment]
The LDAK developer kindly revived the link, so GenoPred should work again now.
