### ISSUE TITLE
Error harmonizing the summary statistics

### ISSUE THREAD

**Issue by XaviFar** [opain/GenoPred#118]
Hi!

While working with the tool I have encountered an issue with the summary statistics that have a hashtag in the header, which often happens with GWAS from Plink for instance. The software does not recognize the #CHR because it is not in the dictionary.

```
Reading in sumstats.
GWAS contains 12195847 variants.
---------------
 Original                   Interpreted Keep  Reason         Description             
 #CHR                       NA          FALSE Not recognised <NA>  
```

The SNP column has not rsid but CHR:POS:A1:A2, But the program continues, tries to match the data with the reference:

```
After removal of variants that are not SNPs or are ambiguous, 9710106 variants remain.
After matching variants to the reference,  variants remain.
0 variants were flipped to match reference.
INFO column is not present.
FREQ  column is not present.
REF.FREQ  column is not present.
```

and the next step gives back an error saying a column is not present, most likely because the result of the merge is an empty table.

Maybe it would be useful to add a previous step removing the hashtag if the header begins with that, and adding a check to see if the result of the merge is not an empty table.

Thanks for this awesome tool.

**Comment by opain** [comment]
Thank you for making this excellent suggestion. I have just pushed a new release (https://github.com/opain/GenoPred/releases/tag/v2.2.11) which will allow for the '#CHR' column name, and it will also allow for when the SNP column contains only CHR:BP:A1:A2 information (no RSIDs) - It will retrieve CHR and BP from the SNP column if the CHR and BP columns are not present.
