### ISSUE TITLE
Scripts/polygenic_score_file_creator_dense/polygenic_score_file_creator_dense.R path issue

### ISSUE THREAD

**Issue by remomomo** [opain/GenoPred#27]
Hi,

I'm running into an issue with Scripts/polygenic_score_file_creator_dense/polygenic_score_file_creator_dense.R

I'm trying to run the step **4.2.3 Dense thresholding** of GenoPred, working with PRSice version 2.3.3

The script crashes with the following error message:

```
Error in fread(paste0(opt$output, "ref_score.all.score"), header = T) :
  File 'resources/Geno_1KG/Score_files_for_polygenic/pt_clump_dense/GCST000998/1KGPhase3.w_hm3.GCST000998ref_score.all.score' does not exist or is non-readable.
Execution halted
```

I checked the respective directory, and there appears to be a file called `1KGPhase3.w_hm3.GCST000998ref_score.all_score` (underscore instead of "."). I'm assuming this is an intermediate file from PRSice, which might have changed names in a more recent version than the one you originally used.

you could change line https://github.com/opain/GenoPred/blob/fc9af075fef1311e90265905779a8a0f9b7b811c/Scripts/polygenic_score_file_creator_dense/polygenic_score_file_creator_dense.R#L241 to handle both cases:

```
if (file.exists(paste0(opt$output,'ref_score.all.score')){
    scores<-fread(paste0(opt$output,'ref_score.all.score'), header=T)
} else {
    scores<-fread(paste0(opt$output,'ref_score.all_score'), header=T)
}
```

similarly for this line https://github.com/opain/GenoPred/blob/fc9af075fef1311e90265905779a8a0f9b7b811c/Scripts/polygenic_score_file_creator_dense/polygenic_score_file_creator_dense.R#L267 

I hope merely the file name has changed and not its contents. Would be great if you could add this as a quick fix!

thank you

**Comment by opain** [comment]
Hi Remo,

Apologies for not replying to this earlier. Thank you for reporting the error, and providing a solution! I have now included your solution in the script.

Many thanks,

Ollie
