### ISSUE TITLE
Error : library and qctools

### ISSUE THREAD

**Issue by jeantristanb** [opain/GenoPred#55]

**Comment by jeantristanb** [comment]
Dear,
I have different issue when I used example :

       Rscript ../Scripts/geno_to_plink/geno_to_plink.R       --target test_data/target/imputed_sample_bgen/example.chr22       --format samp_imp_bgen       --ref resources/data/1kg/1KGPhase3.w_hm3.chr22       --plink2 plink2       --qctool2 resources/software/qctool2/qctool       --liftover resources/software/liftover/liftover       --liftover_track resources/data/liftover/hg18ToHg19.over.chain.gz       --out resources/data/target_output/example_bgen/example_bgen.hm3.chr22
     (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Error in library("colorout") : there is no package called ‘colorout’

it is look like that software don't find library colorout?

    qctools_v2 : you are dowload you're own version, but searching specific place for it's library and depend of what type of os that you are
    I install manually plink2.
    JT

**Comment by opain** [comment]
Dear JT, apologies for not seeing this sooner. I need to look into why I am not receiving notifications of issues!

I am not sure why you are getting the error regarding the colorout package, as I do not call this package in any of the scripts? Please let me know if you are still receiving this error and I can try and help resolve it.

Regarding qctool_v2. This is a good point and the pipeline currently requires the user to be working on a linux OS. I have recently removed the use of qctool2 from GenoPredPipe, so perhaps this solves you issue anyway. Though other software that is downloaded may still cause issues.

Happy to discuss further if useful.
