### ISSUE TITLE
Unnecessary per-chromosome loop in polygenic_score_file_creator_lassosum_plink2.R

### ISSUE THREAD

**Issue by remomomo** [opain/GenoPred#67]
https://github.com/opain/GenoPred/blob/de69fdf79fd3d9760cb910fc5b6217a3fbe478c2/Scripts/polygenic_score_file_creator_lassosum/polygenic_score_file_creator_lassosum_plink2.R#L244

Hi Ollie,

I believe the loop over the single chromosomes is not necessary here. Correct me if I'm wrong.

cheers,

Remo

**Comment by opain** [comment]
You are absolutely correct. Apologies. The output won't be affected but it will run faster. Thank you for highlighting.

I have just pushed this change: https://github.com/opain/GenoPred/pull/68
