### ISSUE TITLE
Downloading dependencies: Unrecognized  --params overwrite arguments

### ISSUE THREAD

**Issue by Felicia648** [opain/GenoPred#83]
Hi, I was following the Installation document when I encountered a problem with downloading the dependencies using this code:
`snakemake --restart-times 3 -j 1 --use-conda --conda-frontend mamba get_dependencies`

When I ran it, it output the error message "_Change in version of GenoPred detected from v0.0 to v2.1. Use --params overwrite=true to proceed._" so I tried to add ` --params overwrite=true ` to the code as suggested. Unfortunately, the error message "_snakemake: error: unrecognized arguments: --params overwrite=true_" appeared instead.

What did I miss or did wrong? Thanks in advance!

**Comment by opain** [comment]
Hello,

Thank you for raising this. This is to warn users that their version of GenoPred has changed after it has already been run. However, there should be no warning if the user has not run the pipeline before (I will fix this). I also need to update the instructions it shows to overwrite - It should instead be `--config overwrite=true`. So the full command with the current version (2.1.0) would be:

`snakemake --restart-times 3 -j 1 --use-conda --conda-frontend mamba get_dependencies --config overwrite=true`

Sorry for the bug and thank you for contacting me.

**Comment by opain** [comment]
I have resolved the issue in the latest version (v2.1.1)

https://github.com/opain/GenoPred/releases/tag/v2.1.1

Feel free to reopen if need be.
